{
 "title": "jwt-pizza-service-prod",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Revenue / Minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(totalRevenue_total{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Pizzas / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "Pizzas Sold"
    },
    {
     "expr": "pizzaCreationFailures_total{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "Pizza Creation Failures"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "backendLatency_milliseconds{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Factory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "factoryLatency_milliseconds{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service-prod\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Authentication Attempts/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(successfulLogins_total{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(failedLogins_total{source=\"jwt-pizza-service-prod\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP Requests/Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service-prod\", method=\"GET\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(\n  rate(requests_total{source=\"jwt-pizza-service-prod\"}[1m])\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service-prod\", method=\"POST\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service-prod\", method=\"PUT\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service-prod\", method=\"DELETE\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}